package seoulnightmarket.seoulnightmarket;

// DO NOT EDIT: This file is automatically generated.
public class VersionInfo {
    public static final String LIBRARY_VERSION = "";
    public static final String BUILD = "";
}
